"""Initial migration.

Revision ID: 74a06c8ede62
Revises: ca90f74a4338
Create Date: 2024-07-12 13:43:35.674493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a06c8ede62'
down_revision = 'ca90f74a4338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
